#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Nairobi Streetkids
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  We are a non-profit organization tasked with helping Nairobi Streetkids with food, shelter, clothing, and medical expenses
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
 Nairobi Streetkids was founded in 2022 with the aim of helping children living on the streets of Nairobi with a second chance in life. We cater for their food, clothing, medical expenses, and shelter. 
 We also educate a number of them with the help of our donors from across the world. Our aim is to get them all off the streets and into a better life.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: eerickmwangi@gmail.com
org_street_address: 1355 Langata #Please include suite number on the line below
org_address_suite: Suite 900
org_city: Nairobi
org_state: NRB
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  +254
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (254) 7992465

#SOCIAL MEDIA
org_twitter_username: Ricko43271722 
org_github_username: Ric254
org_instagram_username: ricko_mwass

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: Nairobi Streetkids
tinyletter_username: Nairobi-streetkids

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: three

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
